version: '3.5'

networks:
  backend:
    driver: bridge

services:
  api:
    image: cosmtrek/air
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    ports:
      - "${PORT}:8080"
    environment:
      - CASSANDRA_DB_HOST=${CASSANDRA_DB_HOST}
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
      - CASSANDRA_MAX_RETRY_CONNECT=${CASSANDRA_MAX_RETRY_CONNECT}
      - MEMCACHED_SERVER=${MEMCACHED_SERVER}
      - REDIS_SERVER=${REDIS_SERVER}
      - REDIS_PREFIX=${REDIS_PREFIX}
    restart: on-failure
    networks:
      - backend
    depends_on:
      - cassandra
      - redis
      - memcached

  cron:
    image: cosmtrek/air
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    environment:
      - CASSANDRA_DB_HOST=${CASSANDRA_DB_HOST}
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
      - CASSANDRA_MAX_RETRY_CONNECT=${CASSANDRA_MAX_RETRY_CONNECT}
      - DATA_FILE_PATH=${DATA_FILE_PATH}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - CRON_EXIT_ON_ERROR=${CRON_EXIT_ON_ERROR}
      - MEMCACHED_SERVER=${MEMCACHED_SERVER}
      - REDIS_SERVER=${REDIS_SERVER}
      - REDIS_PREFIX=${REDIS_PREFIX}
    restart: on-failure
    networks:
      - backend
    depends_on:
      - cassandra
      - redis
      - memcached
    command: ["-c", ".cron.air.toml"]

  cassandra:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/cassandra:/var/lib/cassandra
    networks:
      - backend

  memcached:
    image: memcached:alpine
    volumes:
      - ${DATA_PATH_HOST}/memcached:/var/lib/memcached
    networks:
      - backend

  redis:
    image: redis:alpine
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    networks:
      - backend

